### ISSUE TITLE
Collections Modified Bug when returning to the root view

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#113]
![image](https://github.com/user-attachments/assets/f96be243-28dc-4e9a-b8ea-9d0c4564f5a1)

Error in extension
: - Collection was modified; enumeration operation may not execute.

**Comment by zadjii-msft** [comment]
I'm VERY confident that this will go away after we switch to a real MMVM (#73) or maybe even after #99. I did the "Recents" terribly
