### ISSUE TITLE
Invisible List Item 

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#155]
I've been noticing some weird behavior where sometimes I see "invisible" list items. 

![image](https://github.com/user-attachments/assets/642e2ea4-9e4b-4fa3-8e48-f7190ea0a21a)

In the screenshot above, I've typed "t" into the search box. Notice how there is no focus on any of the list items and the default command to run is "All Apps" (bottom left) ... this is fairly strange. Clicking enter (executing the default command) doesn't do anything - that is _less_ strange _I guess_.

I've noticed this happen a few times... I don't think it's just a my build is wonky thing.

**Comment by joadoumie** [comment]
![image](https://github.com/user-attachments/assets/c2938be9-e3a1-47b6-a66f-87eea2d602c6)

Even weirder... Here you can see the action is "sample terminal settings" and the top list item IS the sample terminal settings command I'm working on... but... the list item isn't focused.

**Comment by joadoumie** [comment]
Side note -- why does "Spreadsheet Compare" show up when I have "terminal set" typed in. Seems off.

**Comment by zadjii** [comment]
> Side note -- why does "Spreadsheet Compare" show up when I have "terminal set" typed in. Seems off.

Probably because the set of characters `['t','e','r','m','i','n','a','l','','s','e','t']` appears in the subtitle (which is hella long)

**Comment by joadoumie** [comment]
Ahh yeah makes perfect sense. Yeah I'm increasingly leaning towards removing the app descriptions completely - they kinda clutter the UI and don't really help at all.
