### ISSUE TITLE
Form Pages should still show the footer for which extension the user is in

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#194]
Example, for settings, we should still have some indicator to the user that what they are seeing is part of the <insert built-in extension>

![image](https://github.com/user-attachments/assets/f52e8a2e-beba-4bf6-8a72-77a93dde74e0)

Here it would be nice for example to actually know that this is from the built-in shell command.

**Comment by zadjii-msft** [comment]
They do as of #219
