### ISSUE TITLE
List Items should have Icons

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#79]
### Description of the new feature / enhancement

List items should have the opportunity to explicitly list their own icons and not require adopting the iconography from the underlying command.

We just need to update ListItems to properly handle their own explicit icons & titles and to derive from the commands only when they are null.

### Scenario when this would be used?

When a user wants an underlying command and the list item to differ in icons that are shown.

**Comment by zadjii-msft** [comment]
This sounds a lot like the conversations we were having some time ago that went with this diagram

![Image](https://github.com/user-attachments/assets/43b325ac-c014-41f1-a7d6-6cb8558cee91)

(Spicy teams channel, 9/6, 10am)
