### ISSUE TITLE
[Bug] Extension List Page doesn't have persistence of Query String in Filter Box

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#85]
### Description of the new feature / enhancement

Going from list page with a query string to a markdown view and then back to the list page causes the query string to be deleted… no good. We need to preserve this string rather than clearing out the previous query.

### Scenario when this would be used?

NA

**Comment by zadjii-msft** [comment]
Pretty sure this is fixed somewhere in the tree of branches leading to `dev/migrie/f/enable-aliases-again` / 4247a8b64

**Comment by joadoumie** [comment]
Cool -- I'll verify and test once that is in.

**Comment by zadjii-msft** [comment]
Fixed circa #236, or one of the other 8 PRs this week
