### ISSUE TITLE
Investigate DisplayName property in the CommandProvider class

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#87]
### Description of the new feature / enhancement

This is not being used in the UI anywhere (yet)... we should think about this field and remove it if it is superflous.

### Scenario when this would be used?

NA

**Comment by zadjii** [comment]
Pretty confident it was vestigial. Only place I could think it would be useful would be in the settings. But even there, the name of the app itself is probably fine, and/or we can just use the names of the top-level commands

**Comment by joadoumie** [comment]
It may actually be really nice for settings to display that string instead of whatever the app name is. Maybe we can use that as the first string shown & if empty we'll fall back on the package name.

**Comment by zadjii-msft** [comment]
Yea I think we'll leave this in there for now. We're not displaying it anywhere now, but once we start displaying settings, installed command providers, etc, we'll need it.
