### ISSUE TITLE
Implement Windows Settings Search

### ISSUE THREAD

**Issue by plante-msft** [zadjii-msft/PowerToys#94]
### Description of the new feature / enhancement

Implement windows settings search so that it achieves parity with WSB settings search. 

### Scenario when this would be used?

A user wants to search for a specific Windows System Setting and launch to that location in the Windows Settings App

**Comment by joadoumie** [comment]
I've effectively got a reasonable prototype of Windows Settings search in https://github.com/zadjii-msft/PowerToys/tree/joadoumie/windows-services. It works the way that PowerToys settings search works now. It def needs work, but it's reasonable.

@plante-msft @zadjii-msft - we should investigate if this is the **best** way that we can do this. I think there is still a gap.

For example, search for the end task toggle, and you won't get any results in PT Run today.

**Comment by zadjii-msft** [comment]
I'm tempted to close this out, and file a follow up for the February timeframe for "Is this really the best way to search Windows Settings?"

I assumed that what PT Run was doing was comprehensive, but clearly it isn't.
